version: "3"

services:
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - database
    ports:
      - "4000:4000"
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw
    volumes:
      - /app/prisma

  database:
    image: postgres
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Postico
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
